version: "3.4"

services:
  flaskdockerstarterkit:
    image: flaskdockerstarterkit
    build:
      context: .
      dockerfile: ./Dockerfile
      target: debug
    ports:
      - 5500:5500
    volumes:
      - .:/flask_starterkit:cached
    env_file: .env
  debugger:
    image: debugger
    build:
      context: .
      dockerfile: ./Dockerfile
      target: debugger
    ports:
      - 5500:5500
      - 5678:5678
    volumes:
      - .:/flask_starterkit:cached
    env_file: .env
  test-runner:
    image: test-runner
    build:
      context: .
      dockerfile: ./Dockerfile
      target: test
    env_file: .env
